ARG NODE_DOCKER_PORT

FROM node:18-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

USER node

COPY --chown=node:node . .

EXPOSE $NODE_DOCKER_PORT

CMD ["npm", "start"]
