version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: nodejs
    container_name: l10nodejs_consumer
    restart: on-failure
    ports:
      - '$PORT:$PORT'
    environment:
      - HOST=$HOST
      - PORT=$PORT
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    networks:
      - l10net
networks:
  l10net:
    external: true
